remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

locale: "en-US"
title: "Tam Yu Fung"
title_separator: "-"
name: "Tam Yu Fung"
description: "Recent projects by Tam Yu Fung"

author:
  name: "Tam Yu Fung"
  avatar: "https://avatars3.githubusercontent.com/u/4027357"
  bio: "Data analytics professional with global project management experience. I am excited about putting together data solutions that generate actionable insights, helping individuals and businesses make optimal decisions."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/tamyufung/"

defaults:
  - values:
      layout: single
      author_profile: true
