title: TAM Yu Fung
logo: "https://avatars3.githubusercontent.com/u/4027357"
description:
  Data analytics professional with global project management experience. I am excited about putting together data solutions that generate actionable insights, helping individuals and businesses make optimal decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/tamyufung/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
