title: TAM Yu Fung
logo: "https://avatars3.githubusercontent.com/u/4027357"
description:
  Being a junior data scientist with 5+ years project management experience enables me to analyse, build and deploy machine learning models within given constraints. I seek to shorten the cycle time of analytics development in alignment with business goals, so that individuals and businesses can make better and faster decisions. 
  <br><br>
  <a href="https://www.linkedin.com/in/tamyufung/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
