remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings

locale: "en-US"
title: "Tam Yu Fung"
title_separator: "-"
name: "Tam Yu Fung"
description: "Recent projects by Tam Yu Fung"
url: "https://yufung.github.io"
logo: "https://raw.githubusercontent.com/yufung/yufung.github.io/master/avatar.jpg"

author:
  name: "Tam Yu Fung"
  avatar: "https://raw.githubusercontent.com/yufung/yufung.github.io/master/avatar.jpg"
  bio: "Data analytics professional with global project management experience. I am excited about putting together data solutions that generate actionable insights, helping individuals and businesses make optimal decisions."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tamyufung/"

titles_from_headings:
  strip_title: true

defaults:
  - values:
      layout: single
      author_profile: true
